-- KPM database schema for local trial and future migrations.
-- Current scope: V1 pilot modules that need to match the approved prototype.

DROP TABLE IF EXISTS kpm_customer_portal_messages CASCADE;
DROP TABLE IF EXISTS kpm_project_announcements CASCADE;
DROP TABLE IF EXISTS kpm_customer_portal_otps CASCADE;
DROP TABLE IF EXISTS kpm_internal_messages CASCADE;
DROP TABLE IF EXISTS kpm_notification_events CASCADE;
DROP TABLE IF EXISTS kpm_order_histories CASCADE;
DROP TABLE IF EXISTS kpm_orders CASCADE;
DROP TABLE IF EXISTS kpm_task_comments CASCADE;
DROP TABLE IF EXISTS kpm_customer_email_outbox CASCADE;
DROP TABLE IF EXISTS kpm_task_attachments CASCADE;
DROP TABLE IF EXISTS kpm_task_participants CASCADE;
DROP TABLE IF EXISTS kpm_task_assignees CASCADE;
DROP TABLE IF EXISTS kpm_tasks CASCADE;
DROP TABLE IF EXISTS kpm_requirements CASCADE;
DROP TABLE IF EXISTS kpm_project_customers CASCADE;
DROP TABLE IF EXISTS kpm_customer_followups CASCADE;
DROP TABLE IF EXISTS kpm_customer_materials CASCADE;
DROP TABLE IF EXISTS kpm_customer_contacts CASCADE;
DROP TABLE IF EXISTS kpm_customer_owners CASCADE;
DROP TABLE IF EXISTS kpm_customers CASCADE;
DROP TABLE IF EXISTS kpm_project_materials CASCADE;
DROP TABLE IF EXISTS kpm_stage_records CASCADE;
DROP TABLE IF EXISTS kpm_stage_materials CASCADE;
DROP TABLE IF EXISTS kpm_stage_assignees CASCADE;
DROP TABLE IF EXISTS kpm_project_stages CASCADE;
DROP TABLE IF EXISTS kpm_project_members CASCADE;
DROP TABLE IF EXISTS kpm_project_skus CASCADE;
DROP TABLE IF EXISTS kpm_projects CASCADE;
DROP TABLE IF EXISTS kpm_template_stages CASCADE;
DROP TABLE IF EXISTS kpm_process_templates CASCADE;
DROP TABLE IF EXISTS kpm_task_status_transitions CASCADE;
DROP TABLE IF EXISTS kpm_enum_items CASCADE;
DROP TABLE IF EXISTS kpm_prototype_snapshots CASCADE;
DROP TABLE IF EXISTS kpm_geocode_cache CASCADE;
DROP TABLE IF EXISTS kpm_user_permissions CASCADE;
DROP TABLE IF EXISTS kpm_role_permissions CASCADE;
DROP TABLE IF EXISTS kpm_user_roles CASCADE;
DROP TABLE IF EXISTS kpm_permissions CASCADE;
DROP TABLE IF EXISTS kpm_roles CASCADE;
DROP TABLE IF EXISTS kpm_user_departments CASCADE;
DROP TABLE IF EXISTS kpm_users CASCADE;
DROP TABLE IF EXISTS kpm_departments CASCADE;
DROP SEQUENCE IF EXISTS kpm_task_no_seq;

CREATE TABLE kpm_departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_kpm_departments_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE kpm_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  password_hash TEXT NOT NULL DEFAULT '{noop}123456',
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_kpm_users_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE kpm_notification_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  aggregate_type TEXT NOT NULL,
  aggregate_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  recipient_user_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'PENDING',
  retry_count INT NOT NULL DEFAULT 0,
  locked_at TIMESTAMP,
  last_error TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at TIMESTAMP
);

CREATE TABLE kpm_internal_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_user_id BIGINT NOT NULL REFERENCES kpm_users(id),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  message_type TEXT NOT NULL DEFAULT 'system',
  source_event_id TEXT,
  read_flag BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  read_at TIMESTAMP
);


CREATE TABLE kpm_user_departments (
  user_id BIGINT NOT NULL REFERENCES kpm_users(id) ON DELETE CASCADE,
  department_id BIGINT NOT NULL REFERENCES kpm_departments(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, department_id)
);

CREATE TABLE kpm_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  role_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_kpm_roles_type CHECK (role_type IN ('GLOBAL', 'PROJECT')),
  CONSTRAINT chk_kpm_roles_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE kpm_user_roles (
  user_id BIGINT NOT NULL REFERENCES kpm_users(id) ON DELETE CASCADE,
  role_id BIGINT NOT NULL REFERENCES kpm_roles(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE kpm_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  permission_type TEXT NOT NULL,
  target TEXT NOT NULL,
  location TEXT NOT NULL,
  CONSTRAINT chk_kpm_permissions_type CHECK (permission_type IN ('MENU', 'BUTTON'))
);

CREATE TABLE kpm_role_permissions (
  role_id BIGINT NOT NULL REFERENCES kpm_roles(id) ON DELETE CASCADE,
  permission_id BIGINT NOT NULL REFERENCES kpm_permissions(id) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE kpm_user_permissions (
  user_id BIGINT NOT NULL REFERENCES kpm_users(id) ON DELETE CASCADE,
  permission_id BIGINT NOT NULL REFERENCES kpm_permissions(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, permission_id)
);

CREATE TABLE kpm_enum_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enum_type TEXT NOT NULL,
  name TEXT NOT NULL,
  value TEXT NOT NULL,
  label_en TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INT NOT NULL DEFAULT 0,
  UNIQUE (enum_type, value),
  CONSTRAINT chk_kpm_enum_items_type CHECK (enum_type ~ '^[a-z][a-z0-9_]{1,63}$'),
  CONSTRAINT chk_kpm_enum_items_value CHECK (value ~ '^[A-Z][A-Z0-9_]{0,63}$')
);

CREATE TABLE kpm_prototype_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state JSONB NOT NULL,
  updated_by TEXT NOT NULL DEFAULT 'system',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kpm_geocode_cache (
  query TEXT PRIMARY KEY,
  latitude NUMERIC(10, 7) NOT NULL,
  longitude NUMERIC(10, 7) NOT NULL,
  display_name TEXT,
  provider TEXT NOT NULL,
  precision TEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE kpm_task_no_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE kpm_task_status_transitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_status TEXT NOT NULL,
  to_status TEXT NOT NULL,
  UNIQUE (from_status, to_status),
  CONSTRAINT chk_kpm_task_transition_from CHECK (from_status ~ '^[A-Z][A-Z0-9_]{0,63}$'),
  CONSTRAINT chk_kpm_task_transition_to CHECK (to_status ~ '^[A-Z][A-Z0-9_]{0,63}$')
);

CREATE TABLE kpm_process_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  scope TEXT NOT NULL,
  status TEXT NOT NULL,
  updated_at DATE NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT chk_kpm_process_templates_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE kpm_template_stages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id BIGINT NOT NULL REFERENCES kpm_process_templates(id) ON DELETE CASCADE,
  stage_name TEXT NOT NULL,
  sort_order INT NOT NULL
);

CREATE TABLE kpm_projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_name TEXT NOT NULL,
  internal_name TEXT NOT NULL,
  model_name TEXT NOT NULL,
  manager_user_id BIGINT REFERENCES kpm_users(id),
  manager_account TEXT NOT NULL,
  process_template_id BIGINT REFERENCES kpm_process_templates(id),
  archived BOOLEAN NOT NULL DEFAULT FALSE,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kpm_project_skus (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES kpm_projects(id) ON DELETE CASCADE,
  whole_machine_part_number TEXT NOT NULL,
  configuration_name TEXT NOT NULL,
  memory_type TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kpm_project_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES kpm_projects(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES kpm_users(id),
  user_account TEXT NOT NULL,
  role_name TEXT NOT NULL
);

CREATE TABLE kpm_project_stages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES kpm_projects(id) ON DELETE CASCADE,
  stage_name TEXT NOT NULL,
  stage_order INT NOT NULL,
  status TEXT NOT NULL DEFAULT 'NOT_STARTED',
  CONSTRAINT chk_kpm_project_stages_status CHECK (status ~ '^[A-Z][A-Z0-9_]{0,63}$')
);

CREATE TABLE kpm_stage_assignees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stage_id BIGINT NOT NULL REFERENCES kpm_project_stages(id) ON DELETE CASCADE,
  assignee_type TEXT NOT NULL,
  assignee_name TEXT NOT NULL,
  account TEXT,
  user_id BIGINT REFERENCES kpm_users(id)
);

CREATE TABLE kpm_stage_materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stage_id BIGINT NOT NULL REFERENCES kpm_project_stages(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_type TEXT,
  file_size TEXT,
  description TEXT,
  uploader TEXT,
  bucket TEXT,
  object_key TEXT,
  storage_url TEXT,
  storage_category TEXT,
  uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  published_to_project BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT chk_kpm_stage_materials_file_type CHECK (file_type IS NULL OR file_type ~ '^[A-Z][A-Z0-9_]{0,63}$')
);

CREATE TABLE kpm_stage_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stage_id BIGINT NOT NULL REFERENCES kpm_project_stages(id) ON DELETE CASCADE,
  author TEXT NOT NULL,
  content TEXT NOT NULL,
  attachments JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kpm_project_materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES kpm_projects(id) ON DELETE CASCADE,
  source_stage TEXT NOT NULL,
  file_name TEXT NOT NULL,
  file_type TEXT,
  file_size TEXT,
  description TEXT,
  uploader TEXT,
  bucket TEXT,
  object_key TEXT,
  storage_url TEXT,
  storage_category TEXT,
  share_target TEXT NOT NULL DEFAULT 'PROJECT_MATERIALS',
  published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  public_visible BOOLEAN NOT NULL DEFAULT FALSE,
  public_at TIMESTAMP,
  CONSTRAINT chk_kpm_project_materials_file_type CHECK (file_type IS NULL OR file_type ~ '^[A-Z][A-Z0-9_]{0,63}$')
);

CREATE TABLE kpm_project_announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES kpm_projects(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  announcement_type TEXT NOT NULL DEFAULT 'GENERAL',
  publisher TEXT,
  published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  announcement_status TEXT NOT NULL DEFAULT 'PUBLISHED',
  retracted_at TIMESTAMP,
  retracted_by TEXT,
  CONSTRAINT chk_kpm_project_announcements_type CHECK (announcement_type ~ '^[A-Z][A-Z0-9_]{0,63}$'),
  CONSTRAINT chk_kpm_project_announcements_status CHECK (announcement_status IN ('PUBLISHED', 'RETRACTED'))
);

CREATE TABLE kpm_customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  short_name TEXT NOT NULL,
  region TEXT NOT NULL,
  address TEXT,
  level TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_kpm_customers_short_name CHECK (short_name ~ '^[A-Z]{1,5}$'),
  CONSTRAINT uk_kpm_customers_short_name UNIQUE (short_name),
  CONSTRAINT chk_kpm_customers_level_code CHECK (level ~ '^[A-Z][A-Z0-9_]{0,63}$'),
  CONSTRAINT chk_kpm_customers_status_code CHECK (status ~ '^[A-Z][A-Z0-9_]{0,63}$')
);

CREATE TABLE kpm_customer_owners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES kpm_customers(id) ON DELETE CASCADE,
  owner_type TEXT NOT NULL,
  owner_user_id BIGINT REFERENCES kpm_users(id),
  owner_name TEXT NOT NULL
);

CREATE TABLE kpm_customer_contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES kpm_customers(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  title TEXT,
  phone TEXT,
  email TEXT,
  remark TEXT
);

CREATE TABLE kpm_customer_materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES kpm_customers(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_type TEXT,
  file_size TEXT,
  uploader TEXT,
  bucket TEXT,
  object_key TEXT,
  storage_url TEXT,
  storage_category TEXT,
  uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_kpm_customer_materials_file_type CHECK (file_type IS NULL OR file_type ~ '^[A-Z][A-Z0-9_]{0,63}$')
);

CREATE TABLE kpm_customer_followups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES kpm_customers(id) ON DELETE CASCADE,
  author TEXT NOT NULL,
  content TEXT NOT NULL,
  attachments JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kpm_project_customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES kpm_projects(id) ON DELETE CASCADE,
  customer_id BIGINT NOT NULL REFERENCES kpm_customers(id) ON DELETE CASCADE,
  project_status TEXT NOT NULL,
  UNIQUE(project_id, customer_id),
  CONSTRAINT chk_kpm_project_customers_status CHECK (project_status ~ '^[A-Z][A-Z0-9_]{0,63}$')
);

CREATE TABLE kpm_requirements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES kpm_projects(id) ON DELETE CASCADE,
  customer_id BIGINT NOT NULL REFERENCES kpm_customers(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  user_story TEXT,
  business_value TEXT,
  acceptance TEXT,
  priority TEXT NOT NULL,
  status TEXT NOT NULL,
  proposer TEXT,
  creator TEXT,
  created_date DATE NOT NULL DEFAULT CURRENT_DATE,
  task_id BIGINT,
  CONSTRAINT chk_kpm_requirements_priority CHECK (priority ~ '^[A-Z][A-Z0-9_]{0,63}$'),
  CONSTRAINT chk_kpm_requirements_status CHECK (status ~ '^[A-Z][A-Z0-9_]{0,63}$')
);

CREATE TABLE kpm_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_no TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT,
  project_id BIGINT REFERENCES kpm_projects(id) ON DELETE SET NULL,
  stage_id BIGINT REFERENCES kpm_project_stages(id) ON DELETE SET NULL,
  category TEXT NOT NULL,
  status TEXT NOT NULL,
  priority TEXT NOT NULL,
  creator_user_id BIGINT REFERENCES kpm_users(id),
  creator TEXT NOT NULL,
  expected_completion_at DATE,
  due_date DATE,
  source TEXT NOT NULL DEFAULT 'TASK_MANAGEMENT',
  customer_id BIGINT REFERENCES kpm_customers(id) ON DELETE SET NULL,
  blocked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_kpm_tasks_category CHECK (category ~ '^[A-Z][A-Z0-9_]{0,63}$'),
  CONSTRAINT chk_kpm_tasks_status CHECK (status ~ '^[A-Z][A-Z0-9_]{0,63}$'),
  CONSTRAINT chk_kpm_tasks_priority CHECK (priority ~ '^[A-Z][A-Z0-9_]{0,63}$'),
  CONSTRAINT chk_kpm_tasks_source CHECK (source IN (
    'TASK_MANAGEMENT','STAGE_DETAIL','CUSTOMER_PORTAL','REQUIREMENT_AUTO_CREATED',
    'CUSTOMER_FOLLOW_UP','CUSTOMER_REQUIREMENT_BREAKDOWN','CUSTOMER_PROJECT_FOLLOW_UP',
    'TEST_DATA','INTEGRATION_SCRIPT'
  ))
);

CREATE TABLE kpm_customer_portal_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES kpm_customers(id) ON DELETE CASCADE,
  contact_id BIGINT REFERENCES kpm_customer_contacts(id) ON DELETE SET NULL,
  contact_email TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  message_type TEXT NOT NULL DEFAULT 'system',
  project_id BIGINT REFERENCES kpm_projects(id) ON DELETE SET NULL,
  task_id BIGINT REFERENCES kpm_tasks(id) ON DELETE SET NULL,
  announcement_id BIGINT REFERENCES kpm_project_announcements(id) ON DELETE SET NULL,
  read_flag BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  read_at TIMESTAMP
);

CREATE TABLE kpm_task_assignees (
  task_id BIGINT NOT NULL REFERENCES kpm_tasks(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES kpm_users(id),
  assignee_name TEXT NOT NULL,
  PRIMARY KEY (task_id, assignee_name)
);

CREATE TABLE kpm_task_participants (
  task_id BIGINT NOT NULL REFERENCES kpm_tasks(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES kpm_users(id),
  participant_name TEXT NOT NULL,
  PRIMARY KEY (task_id, participant_name)
);

CREATE TABLE kpm_task_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL REFERENCES kpm_tasks(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_type TEXT,
  file_size TEXT,
  uploader TEXT,
  bucket TEXT,
  object_key TEXT,
  storage_url TEXT,
  storage_category TEXT,
  uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_kpm_task_attachments_file_type CHECK (file_type IS NULL OR file_type ~ '^[A-Z][A-Z0-9_]{0,63}$')
);

CREATE TABLE kpm_task_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL REFERENCES kpm_tasks(id) ON DELETE CASCADE,
  author TEXT NOT NULL,
  comment_type TEXT NOT NULL DEFAULT 'internal',
  content TEXT NOT NULL,
  attachments JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kpm_customer_email_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_email TEXT NOT NULL,
  recipient_name TEXT,
  subject TEXT NOT NULL,
  content TEXT NOT NULL,
  message_type TEXT NOT NULL DEFAULT 'system',
  related_project_id BIGINT REFERENCES kpm_projects(id) ON DELETE SET NULL,
  related_task_id BIGINT REFERENCES kpm_tasks(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  last_error TEXT,
  sent_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kpm_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_date DATE NOT NULL,
  customer_id BIGINT NOT NULL REFERENCES kpm_customers(id),
  project_id BIGINT NOT NULL REFERENCES kpm_projects(id),
  sku_id BIGINT REFERENCES kpm_project_skus(id),
  sku_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  order_type TEXT NOT NULL,
  status TEXT NOT NULL,
  quantity INT NOT NULL,
  specification TEXT NOT NULL,
  expected_ship_date DATE,
  planned_ship_date DATE,
  actual_ship_date DATE,
  software_version TEXT,
  currency TEXT NOT NULL,
  unit_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
  creator_user_id BIGINT REFERENCES kpm_users(id),
  creator TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_kpm_orders_type CHECK (order_type ~ '^[A-Z][A-Z0-9_]{0,63}$'),
  CONSTRAINT chk_kpm_orders_status CHECK (status ~ '^[A-Z][A-Z0-9_]{0,63}$'),
  CONSTRAINT chk_kpm_orders_currency CHECK (currency ~ '^[A-Z][A-Z0-9_]{0,15}$')
);

CREATE TABLE kpm_order_histories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES kpm_orders(id) ON DELETE CASCADE,
  modifier TEXT NOT NULL,
  modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  changes TEXT NOT NULL,
  reason TEXT NOT NULL
);

CREATE INDEX idx_kpm_projects_search ON kpm_projects (external_name, internal_name, model_name);
CREATE INDEX idx_kpm_tasks_status ON kpm_tasks (status, category);
CREATE INDEX idx_kpm_tasks_task_no ON kpm_tasks (task_no);
CREATE INDEX idx_kpm_orders_date ON kpm_orders (order_date);
CREATE INDEX idx_kpm_customers_region ON kpm_customers (region);
CREATE INDEX idx_kpm_notification_events_status ON kpm_notification_events (status, created_at);
CREATE INDEX idx_kpm_internal_messages_recipient ON kpm_internal_messages (recipient_user_id, read_flag, created_at);
CREATE INDEX idx_kpm_project_announcements_project ON kpm_project_announcements (project_id, published_at DESC);
CREATE INDEX idx_kpm_customer_portal_messages_contact ON kpm_customer_portal_messages (lower(contact_email), read_flag, created_at DESC);
CREATE INDEX idx_kpm_customer_email_outbox_status ON kpm_customer_email_outbox (status, created_at DESC);

-- Common fields required by Kozen/KPM backend coding standard.
-- Pilot compatibility note:
-- Current V1 tables still use string business identifiers as primary keys because the frontend and
-- cross-table references already depend on them. The next schema refactor should promote BIGSERIAL
-- `id` to the technical primary key and move these strings to business-code columns.
DO $$
DECLARE
  table_name text;
BEGIN
  FOR table_name IN
    SELECT tablename
    FROM pg_tables
    WHERE schemaname = 'public'
      AND tablename LIKE 'kpm_%'
  LOOP
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS creator TEXT', table_name);
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS updator TEXT', table_name);
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP', table_name);
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP', table_name);
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS del_flag SMALLINT NOT NULL DEFAULT 0', table_name);
  END LOOP;
END $$;

-- Performance indexes for list pages, dashboards and customer portal.
CREATE INDEX IF NOT EXISTS idx_kpm_users_active_name ON kpm_users (name) WHERE del_flag=0;
CREATE INDEX IF NOT EXISTS idx_kpm_users_active_account_email ON kpm_users (account, email) WHERE del_flag=0;
CREATE INDEX IF NOT EXISTS idx_kpm_user_departments_department ON kpm_user_departments (department_id, del_flag, user_id);
CREATE INDEX IF NOT EXISTS idx_kpm_user_roles_role ON kpm_user_roles (role_id, del_flag, user_id);
CREATE INDEX IF NOT EXISTS idx_kpm_role_permissions_permission ON kpm_role_permissions (permission_id, del_flag, role_id);
CREATE INDEX IF NOT EXISTS idx_kpm_user_permissions_permission ON kpm_user_permissions (permission_id, del_flag, user_id);
CREATE INDEX IF NOT EXISTS idx_kpm_enum_items_lookup ON kpm_enum_items (enum_type, value, active, del_flag);
CREATE INDEX IF NOT EXISTS idx_kpm_enum_items_order ON kpm_enum_items (enum_type, active, del_flag, sort_order, id);
CREATE INDEX IF NOT EXISTS idx_kpm_projects_list ON kpm_projects (del_flag, archived, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_projects_manager ON kpm_projects (manager_user_id, del_flag);
CREATE INDEX IF NOT EXISTS idx_kpm_projects_process_template ON kpm_projects (process_template_id, del_flag);
CREATE INDEX IF NOT EXISTS idx_kpm_project_skus_project ON kpm_project_skus (project_id, active, del_flag, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_project_members_project ON kpm_project_members (project_id, del_flag, role_name);
CREATE INDEX IF NOT EXISTS idx_kpm_project_members_user ON kpm_project_members (user_id, del_flag, project_id);
CREATE INDEX IF NOT EXISTS idx_kpm_project_stages_project ON kpm_project_stages (project_id, del_flag, stage_order);
CREATE INDEX IF NOT EXISTS idx_kpm_template_stages_template ON kpm_template_stages (template_id, del_flag, sort_order);
CREATE INDEX IF NOT EXISTS idx_kpm_stage_assignees_stage ON kpm_stage_assignees (stage_id, del_flag, id);
CREATE INDEX IF NOT EXISTS idx_kpm_stage_assignees_user ON kpm_stage_assignees (user_id, del_flag, stage_id);
CREATE INDEX IF NOT EXISTS idx_kpm_stage_materials_stage ON kpm_stage_materials (stage_id, del_flag, uploaded_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_stage_records_stage ON kpm_stage_records (stage_id, del_flag, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_project_materials_project ON kpm_project_materials (project_id, del_flag, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_project_materials_public ON kpm_project_materials (project_id, public_visible, del_flag, public_at DESC, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_project_announcements_project_time ON kpm_project_announcements (project_id, del_flag, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_project_announcements_active_portal ON kpm_project_announcements (project_id, announcement_status, del_flag, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_process_templates_list ON kpm_process_templates (del_flag, updated_at DESC, name);
CREATE INDEX IF NOT EXISTS idx_kpm_customers_list ON kpm_customers (del_flag, name);
CREATE INDEX IF NOT EXISTS idx_kpm_customers_short_name_upper ON kpm_customers (upper(short_name)) WHERE del_flag=0;
CREATE INDEX IF NOT EXISTS idx_kpm_customer_owners_customer_type ON kpm_customer_owners (customer_id, owner_type, del_flag, owner_user_id);
CREATE INDEX IF NOT EXISTS idx_kpm_customer_owners_user ON kpm_customer_owners (owner_user_id, del_flag, customer_id);
CREATE INDEX IF NOT EXISTS idx_kpm_customer_contacts_customer ON kpm_customer_contacts (customer_id, del_flag, name);
CREATE INDEX IF NOT EXISTS idx_kpm_customer_contacts_email ON kpm_customer_contacts (lower(email)) WHERE del_flag=0 AND email IS NOT NULL AND email <> '';
CREATE INDEX IF NOT EXISTS idx_kpm_customer_materials_customer ON kpm_customer_materials (customer_id, del_flag, uploaded_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_customer_followups_customer ON kpm_customer_followups (customer_id, del_flag, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_project_customers_project ON kpm_project_customers (project_id, del_flag, customer_id);
CREATE INDEX IF NOT EXISTS idx_kpm_project_customers_customer ON kpm_project_customers (customer_id, del_flag, project_id);
CREATE INDEX IF NOT EXISTS idx_kpm_requirements_project_customer ON kpm_requirements (project_id, customer_id, del_flag, created_date DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_requirements_project_title ON kpm_requirements (project_id, del_flag, title);
CREATE INDEX IF NOT EXISTS idx_kpm_requirements_task ON kpm_requirements (task_id, del_flag);
CREATE INDEX IF NOT EXISTS idx_kpm_tasks_list ON kpm_tasks (del_flag, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_tasks_status_category_time ON kpm_tasks (status, category, del_flag, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_tasks_project_time ON kpm_tasks (project_id, del_flag, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_tasks_stage_time ON kpm_tasks (stage_id, del_flag, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_tasks_customer_time ON kpm_tasks (customer_id, del_flag, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_tasks_creator_time ON kpm_tasks (creator_user_id, del_flag, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_task_assignees_task ON kpm_task_assignees (task_id, del_flag, assignee_name);
CREATE INDEX IF NOT EXISTS idx_kpm_task_assignees_user ON kpm_task_assignees (user_id, del_flag, task_id);
CREATE INDEX IF NOT EXISTS idx_kpm_task_participants_task ON kpm_task_participants (task_id, del_flag, participant_name);
CREATE INDEX IF NOT EXISTS idx_kpm_task_participants_user ON kpm_task_participants (user_id, del_flag, task_id);
CREATE INDEX IF NOT EXISTS idx_kpm_task_attachments_task ON kpm_task_attachments (task_id, del_flag, uploaded_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_task_comments_task ON kpm_task_comments (task_id, del_flag, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_task_comments_page ON kpm_task_comments (task_id, del_flag, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_task_comments_external ON kpm_task_comments (task_id, comment_type, del_flag, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_orders_list_date ON kpm_orders (del_flag, order_date DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_orders_customer_date ON kpm_orders (customer_id, del_flag, order_date DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_orders_project_date ON kpm_orders (project_id, del_flag, order_date DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_orders_type_status ON kpm_orders (order_type, status, del_flag);
CREATE INDEX IF NOT EXISTS idx_kpm_orders_expected_ship ON kpm_orders (expected_ship_date, del_flag);
CREATE INDEX IF NOT EXISTS idx_kpm_order_histories_order ON kpm_order_histories (order_id, del_flag, modified_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_notification_events_pending ON kpm_notification_events (status, del_flag, created_at);
CREATE INDEX IF NOT EXISTS idx_kpm_internal_messages_recipient_time ON kpm_internal_messages (recipient_user_id, del_flag, read_flag, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_internal_messages_cleanup ON kpm_internal_messages (read_flag, del_flag, read_at);
CREATE UNIQUE INDEX IF NOT EXISTS uk_kpm_internal_messages_event_recipient
  ON kpm_internal_messages (source_event_id, recipient_user_id, message_type)
  WHERE source_event_id IS NOT NULL AND del_flag=0;
CREATE INDEX IF NOT EXISTS idx_kpm_notification_events_claim
  ON kpm_notification_events (status, del_flag, created_at, locked_at)
  WHERE status IN ('PENDING', 'PROCESSING');
CREATE INDEX IF NOT EXISTS idx_kpm_internal_messages_page
  ON kpm_internal_messages (recipient_user_id, del_flag, read_flag, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_customer_portal_messages_customer ON kpm_customer_portal_messages (customer_id, del_flag, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_customer_portal_messages_task ON kpm_customer_portal_messages (task_id, del_flag, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_customer_portal_messages_announcement ON kpm_customer_portal_messages (announcement_id, del_flag, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_customer_email_outbox_status_time ON kpm_customer_email_outbox (status, del_flag, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_customer_portal_messages_contact_time ON kpm_customer_portal_messages (lower(contact_email), del_flag, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uk_kpm_portal_messages_announcement_contact
  ON kpm_customer_portal_messages (announcement_id, lower(trim(contact_email)))
  WHERE announcement_id IS NOT NULL AND del_flag=0;

-- Knowledge base: internal articles and customer portal visibility scopes.
CREATE TABLE IF NOT EXISTS kpm_knowledge_articles (
  id BIGINT PRIMARY KEY,
  title TEXT NOT NULL,
  symptom TEXT NOT NULL,
  root_cause TEXT NOT NULL,
  solution TEXT,
  workaround TEXT,
  attachments JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'PENDING_REVIEW',
  author_user_id BIGINT REFERENCES kpm_users(id),
  author_name TEXT,
  published_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creator TEXT,
  updator TEXT,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  del_flag SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT chk_kpm_knowledge_status CHECK (status IN ('PENDING_REVIEW', 'PUBLISHED')),
  CONSTRAINT chk_kpm_knowledge_solution_or_workaround CHECK (
    coalesce(nullif(trim(solution), ''), nullif(trim(workaround), '')) IS NOT NULL
  )
);

CREATE TABLE IF NOT EXISTS kpm_knowledge_article_projects (
  id BIGINT PRIMARY KEY,
  article_id BIGINT NOT NULL REFERENCES kpm_knowledge_articles(id),
  project_id BIGINT REFERENCES kpm_projects(id),
  project_scope TEXT NOT NULL DEFAULT 'PROJECT',
  creator TEXT,
  updator TEXT,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  del_flag SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS kpm_knowledge_article_customers (
  id BIGINT PRIMARY KEY,
  article_id BIGINT NOT NULL REFERENCES kpm_knowledge_articles(id),
  customer_id BIGINT REFERENCES kpm_customers(id),
  customer_scope TEXT NOT NULL DEFAULT 'CUSTOMER',
  creator TEXT,
  updator TEXT,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  del_flag SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS kpm_knowledge_article_tasks (
  id BIGINT PRIMARY KEY,
  article_id BIGINT NOT NULL REFERENCES kpm_knowledge_articles(id),
  task_id BIGINT NOT NULL REFERENCES kpm_tasks(id),
  creator TEXT,
  updator TEXT,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  del_flag SMALLINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_kpm_knowledge_articles_page ON kpm_knowledge_articles (del_flag, status, updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_kpm_knowledge_articles_search ON kpm_knowledge_articles USING gin (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(symptom, '') || ' ' || coalesce(root_cause, '')));
CREATE INDEX IF NOT EXISTS idx_kpm_knowledge_article_projects_article ON kpm_knowledge_article_projects (article_id, del_flag);
CREATE INDEX IF NOT EXISTS idx_kpm_knowledge_article_projects_project ON kpm_knowledge_article_projects (project_id, del_flag, article_id);
CREATE INDEX IF NOT EXISTS idx_kpm_knowledge_article_customers_article ON kpm_knowledge_article_customers (article_id, del_flag);
CREATE INDEX IF NOT EXISTS idx_kpm_knowledge_article_customers_customer ON kpm_knowledge_article_customers (customer_id, customer_scope, del_flag, article_id);
CREATE INDEX IF NOT EXISTS idx_kpm_knowledge_article_tasks_task ON kpm_knowledge_article_tasks (task_id, del_flag, article_id);

-- Additional indexes for task dashboard statistics and analytics dashboards.
CREATE INDEX IF NOT EXISTS idx_kpm_tasks_creator_status_active ON kpm_tasks (creator_user_id, status, created_at DESC, id DESC) WHERE del_flag = 0;
CREATE INDEX IF NOT EXISTS idx_kpm_tasks_customer_status_active ON kpm_tasks (customer_id, status, created_at DESC, id DESC) WHERE del_flag = 0 AND customer_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_kpm_task_assignees_user_task_active ON kpm_task_assignees (user_id, task_id) WHERE del_flag = 0 AND user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_kpm_task_participants_user_task_active ON kpm_task_participants (user_id, task_id) WHERE del_flag = 0 AND user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_kpm_orders_analytics_active ON kpm_orders (order_date, project_id, customer_id, currency) INCLUDE (amount, quantity) WHERE del_flag = 0;
CREATE INDEX IF NOT EXISTS idx_kpm_orders_customer_latest_active ON kpm_orders (customer_id, order_date DESC) WHERE del_flag = 0;
CREATE INDEX IF NOT EXISTS idx_kpm_customer_followups_latest_active ON kpm_customer_followups (customer_id, created_at DESC) WHERE del_flag = 0;
CREATE INDEX IF NOT EXISTS idx_kpm_project_customers_customer_project_active ON kpm_project_customers (customer_id, project_id) WHERE del_flag = 0;
CREATE INDEX IF NOT EXISTS idx_kpm_project_customers_project_customer_active ON kpm_project_customers (project_id, customer_id) WHERE del_flag = 0;
CREATE INDEX IF NOT EXISTS idx_kpm_customer_owners_type_user_customer_active ON kpm_customer_owners (owner_type, owner_user_id, customer_id) WHERE del_flag = 0;
