-- Project announcements, customer portal messages, Redis OTP cleanup, and removal of obsolete salesability fields.

ALTER TABLE kpm_projects
  DROP COLUMN IF EXISTS salesability,
  DROP COLUMN IF EXISTS unsellable_reason;

UPDATE kpm_enum_items
SET del_flag=1, active=false, update_time=current_timestamp
WHERE enum_type IN ('salesability', 'unsellable_reason');

DROP TABLE IF EXISTS kpm_customer_portal_otps;

CREATE TABLE IF NOT EXISTS kpm_project_announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES kpm_projects(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  announcement_type TEXT NOT NULL DEFAULT 'GENERAL',
  publisher TEXT,
  published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creator TEXT,
  updator TEXT,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  del_flag SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS kpm_customer_portal_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES kpm_customers(id) ON DELETE CASCADE,
  contact_id BIGINT REFERENCES kpm_customer_contacts(id) ON DELETE SET NULL,
  contact_email TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  message_type TEXT NOT NULL DEFAULT 'system',
  project_id BIGINT REFERENCES kpm_projects(id) ON DELETE SET NULL,
  task_id BIGINT REFERENCES kpm_tasks(id) ON DELETE SET NULL,
  announcement_id BIGINT REFERENCES kpm_project_announcements(id) ON DELETE SET NULL,
  read_flag BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  read_at TIMESTAMP,
  creator TEXT,
  updator TEXT,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  del_flag SMALLINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_kpm_project_announcements_project
  ON kpm_project_announcements (project_id, published_at DESC)
  WHERE del_flag=0;

CREATE INDEX IF NOT EXISTS idx_kpm_customer_portal_messages_contact
  ON kpm_customer_portal_messages (lower(contact_email), read_flag, created_at DESC)
  WHERE del_flag=0;

INSERT INTO kpm_permissions (id, code, name, permission_type, target, location)
VALUES (3097,'button:project-detail:publish-announcement','项目详情 / 发布公告','BUTTON','发布公告','项目详情')
ON CONFLICT (code) DO UPDATE SET
  name=excluded.name, permission_type=excluded.permission_type, target=excluded.target, location=excluded.location, del_flag=0, update_time=current_timestamp;

INSERT INTO kpm_role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM kpm_roles r
JOIN kpm_permissions p ON p.code='button:project-detail:publish-announcement' AND p.del_flag=0
WHERE r.del_flag=0 AND r.name IN ('CTO', '系统管理员', 'SPM', '研发', '运营', '销售', '技术支持')
ON CONFLICT DO NOTHING;
